# Generated by Django 6.0.5 on 2026-05-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the todo item', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the todo item', null=True)),
                ('is_completed', models.BooleanField(default=False, help_text='Whether the todo item is completed')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the todo was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the todo was last updated')),
            ],
            options={
                'verbose_name': 'Todo',
                'verbose_name_plural': 'Todos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='todos_todo_created_1ddebf_idx'), models.Index(fields=['is_completed'], name='todos_todo_is_comp_4f00f7_idx')],
            },
        ),
    ]
